### ISSUE TITLE
Can't get typescript-brunch to use my tsconfig.json

### ISSUE THREAD

**Issue by rikkit** [brunch/typescript-brunch#25]
Hi there,

I've been using brunch with typescript-brunch just fine for a while now. I've just started using async/await in my TS and I've hit a wall when changing the TS target to ES2015.

My directory structure is how brunch new set it up:

```
/app
- application.ts
- ...
/assets
- ...
/public
- ...
tsconfig.json
brunch-config.js
...
```

My tsconfig.json is

```
{
    "compilerOptions": { 
      "target": "es2015",
      "module": "commonjs",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true
    }
}
```

My brunch-config.js is

```
module.exports = {
   npm: {
     globals: {
      $: 'jquery',
      jQuery: 'jquery',
      NProgress: 'nprogress'
  }},
  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /^app/,
        'js/vendor.js': /(^node_modules|^vendor)/ 
      },
      order: {
        before: /.*jquery.js*/
      }
    },
    stylesheets: { joinTo: 'app.css' },
    templates: { joinTo: 'app.js' }
  },
  plugins: {
    sass: {
      options: {
        includePaths: [
          'node_modules/bootstrap-sass/assets/stylesheets/',
          'vendor/'
        ]
      }
    }
  }
}
```

When I do brunch build with the async TS code all I get is

```
error: Compiling of app/application.ts failed.
```

However when I run tsc in the root directory, compilation succeeds.

What am I doing wrong?

**Comment by baptistedonaux** [comment]
@rikkit What's the command-line used to compile with ```tsc``` to successful ?

@colinbate Do you have an idea ?

**Comment by rikkit** [comment]
It's simply 'tsc' . It picks up the tsconfig.json just fine. 

I can share the code if that helps?

**Comment by colinbate** [comment]
@rikkit Did it used to work when you were targeting ES5? Was that the only change? If you recently updated your version of brunch-typescript, you may want to add this to your `brunch-config`:

```js
plugins: {
  brunchTypescript: {
    ignoreErrors: true
  }
}
```

**Comment by colinbate** [comment]
Also, are you further transpiling your code after typescript? If your code is public, please post a link as I'd be interested in investigating if the problem is more than the error issue above.

**Comment by colinbate** [comment]
And, one last thing, if all else fails, TypeScript 2.1 supports async/await targetting ES5. I'll see about getting a version of `brunch-typescript` out which supports it.

**Comment by rikkit** [comment]
@colinbate [this is the project](https://github.com/rikkit/homepage/commit/33176d577da8cde11677cbf9bfea15abe4b683cf), nothing special just my personal page. Only thing that's missing is the tsconfig.json file, which I posted above. You can ignore the .net stuff, that's not needed to show the problem with brunch-typsecript.

AFAIK there are no extra compilation steps to the TS files.

For what it's worth, I tried copy pasting my typescript config into the plugins section of my brunch-config.js, that didn't work either - 

```
  plugins: {
    brunchTypescript: {
      "compilerOptions": { 
        "target": "es6",
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
      }
    }
  }
```

I am wondering if me using Windows has anything to do with it. Although I did get the same problems when I tried using the new Bash/Ubuntu tooling on Windows 10.

**Comment by rikkit** [comment]
Hi, after some fiddling about I've upgraded to TS 2.1.4 and added the ignoreErrors property to brunchTypescript config. Still targeting es2015, due to what seems like a problem with one of the other dependencies.

My code seems to work now - though I don't think this resolves the original problem? I'm new to TS so I might just be stumbling on things others find super obvious!
