### ISSUE TITLE
Type definition files compilation should not result in errors

### ISSUE THREAD

**Issue by galenus** [brunch/typescript-brunch#30]
Currently, compiling any .d.ts file will result in error because there is no output from Typescript compiler for such files.

**Comment by ricjac** [comment]
I'm getting the same issue. Is there a work around?

**Comment by CarlosOnline** [comment]
Any fix?

**Comment by ricjac** [comment]
I found a work around:
https://brunch.io/docs/concepts : Put your .d.ts file in the vendor folder. This will copy them in the output directory though.

If you want to https://brunch.io/docs/config#-hooks- : hook into onCompile look up your definition files in changedAssets and change the destination directory to some temp directory.
