### ISSUE TITLE
Allow targetExtension specified in configuration

### ISSUE THREAD

**Issue by jmhdev** [brunch/typescript-brunch#34]
Allowing the developer to specify the target extension in the plugin configuration would allow for plugin output to be passed to babel plugin for custom jsx transformation before writing to file.  My use case is the customized JSX transform required by infernojs.  I added the following to the TypescriptCompiler constructor after mapping of options keys (line 67) , and it worked as expected:

` if(this.options.targetExtension){this.targetExtension = this.options.targetExtension};`

I suppose you could do something like specifying an option in the config like:

`brunchTypescript:{targetJS:true}`

and then add the following to the constructor:

` if(this.options.targetJS){this.targetExtension = ".js"};`

**Comment by shvaikalesh** [comment]
`targetExtension = '.js'` should not require extra config. I don't see reasons for opt-out either.

**Comment by jmhdev** [comment]
Well, in the source code for the plugin, the `targetExtension` is never set.  Even though typescripts compilation process outputs js, without this being specified, Brunch does not seem to recognize that the output of the tsbrunch plugin should/can be passed to babelbrunch for additional processing.  Only after I edited the plugin's source did the tsBrunch output get pushed through babelbrunch for jsx transpiling. Due to the the nature of transpiling infernojs, the tsconfig has to preserve jsx, `jsx:"preserve"`.  

This results in the tsBrunch output being written to `app.js` (or whatever the bundle file is called) without the jsx being transformed into the appropriate function calls.  I can post same code, brunch config, and output if you'd like.  Maybe I have something configured incorrectly.  But, the process only worked when I edited the tsBrunch source with `TypescriptCompiler.prototype.targetExtension = ".js" did the tsBrunch output get passed to babelBrunch for the additional transpiling.  I later changed my edits to make it a configurable option.

The Brunch Docs even specify that targetExtension is for chaining purposes:

"Property: targetExtension

String. Convenience for making chains of compilers. Specifies the new extension of processed file. For example, less-brunch changes .less to .css so postcss-brunch matches file by extension."

Also, I think it should be left as an option and not a default.  I am not sure of the reason, but a dev might not want their tsBrunch output with any other plugins.

Anyways, thanks for the response.  Let me know if you want me to post my code,config, etc. so that you could point me to what is set up incorrectly (that could very well be my problem).  At the very least, I have a working solution, but though others might find a simple config option helpful for the same purpose, if none currently exists.

**Comment by shvaikalesh** [comment]
Sorry, my wording was a bit confusing. I think we should have

```js
TypescriptCompiler.prototype.targetExtension = ".js"
```

in this plugin on-by-default without opt-out unless we would have an issue with a good reason why 

>  a dev might not want their tsBrunch output with any other plugins.

**Comment by jmhdev** [comment]
I think that sounds good.  Perhaps:

`targetJS:true` as a default.

the constructor function could do a simple condition check for existence of option, and then for false/true.

` if (config.targetJS === true | config.targetJS === undefined){ this.targetExtension = ".js" }

something like that...

**Comment by shvaikalesh** [comment]
Fixed by #39
